require 'bundler'
Bundler.setup(:default, ENV['SIM_ENV'])
require 'sim'

require 'simplecov' if %w(test).include? ENV['SIM_ENV']

require_relative 'event/bot_move'
require_relative 'event/move'
require_relative 'event/sim_field'
require_relative 'field'
require_relative 'world'
require_relative 'animal'
require_relative 'herbivore'
require_relative 'predator'
require_relative 'vegetation'
require_relative 'flora'
require_relative 'player/base'
require_relative 'player/member'
require_relative 'player/admin'
require_relative 'view'
require_relative 'builder/flora_fauna'
require_relative 'builder/vegetation'
require_relative 'builder/world'
require_relative 'builder/dropzone'
require_relative 'death'
