language: ruby

rvm:
  - 2.2.1

services:
  - mongodb

addons:
  code_climate:
    repo_token:
      secure: "ArhwSUxvZFVmLDMJNYO/bTPkztBaGppHQFoHxHilY3zDx5Oyonx0M1h5zF08eVDOGWbCNm0ssJVVhbLxokVSqah0osFue9WrkYMd3VXVKFDLUujHWVTM+pUBKr3/VgS7yv8jV5vdocwPlGY53VIOb1Zi4VadPQl5UVqwFVJ+RT4="

bundler_args: --without development

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - mv config/mongoid_example.yml config/mongoid.yml
  - mv config/secrets_example.yml config/secrets.yml
  - mv config/level_example.yml config/level.yml
  - mkdir tmp
  - mkdir tmp/sockets

branches:
  only:
    - master
    - production
