time_unit: 5
sim_loop:
  duration: 25
world:
  width: 15
  height: 15
  vegetation:
    classes: default/vegetation.yml
    builder: test/vegetation_builder.yml
  flora:
    classes: default/flora.yml
    builder: test/flora_builder.yml
  fauna:
    classes: default/animal.yml
    builder: test/fauna_builder.yml
dropzones:
  bot_1:
    from:  0
    to:    3
  gateway:
    from:  4
    to:    6
  transit:
    from:  7
    to:    9
  players:
    from: 10
    to:   12
  bot_2:
    from: 13
    to:   15
